name: imam_hossain
description: "A personal portfolio project for Imam Hossain"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^8.2.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  url_strategy: ^0.2.0
  google_fonts: ^6.2.1
  path: ^1.9.0
  rxdart: ^0.28.0
  get_it: ^8.0.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.2.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^3.0.2
  json_serializable: ^6.9.4
  easy_localization_loader: ^2.0.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/

  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/Custom-Icons.ttf

flutter_native_splash:
  color: "#CD5758"
  image: "assets/images/splash-rocket.apng"
  color_dark: "#CD5758"
  image_dark: "assets/images/splash-rocket.apng"

flutter_launcher_icons:
  image_path: "assets/images/app-icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app-icon.png"
    background_color: "#CD5758"
    theme_color: "#CD5758"
  windows:
    generate: true
    image_path: "assets/images/app-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app-icon.png"
