name: imam_hossain
description: "A personal portfolio project for Imam Hossain"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  url_strategy: ^0.2.0
  google_fonts: ^6.2.1
  path: ^1.9.0
  rxdart: ^0.28.0
  get_it: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: BoxIcons
      fonts:
        - asset: assets/fonts/BoxIcons.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: OctIcons
      fonts:
        - asset: assets/fonts/OctIcons.ttf